---
# USERNAME and PASSWORD can be passed in as environment parameters,
# e.g. USERNAME=my@user.cz
# e.g. PASSWORD=my@user.cz

ackee:
  baseUrl: 'http://api.docker1812.zonkej.cz'
  origin: 'http://app.docker1812.zonkej.cz'
  username: 'USERNAME'
  password: 'PASSWORD'

preprod-b:
  baseUrl: 'https://api-preprod-b.zonkej.cz'
  origin: 'https://app-preprod-b.zonkej.cz'
  username: 'USERNAME'
  password: 'PASSWORD'
