---
# USERNAME and PASSWORD can be passed in as environment parameters,
# e.g. USERNAME=my@user.cz
# e.g. PASSWORD=my@user.cz

production:
 baseUrl: 'https://api.zonky.cz'
 origin: 'https://app.zonky.cz'
 username: 'USERNAME'
 password: 'PASSWORD'

preprod:
 baseUrl: 'https://api.zonkej.cz'
 origin: 'https://app.zonkej.cz'
 username: 'USERNAME'
 password: 'PASSWORD'

test:
 baseUrl: 'https://api-test.zonkej.cz'
 origin: 'https://test.zonkej.cz'
 username: 'USERNAME'
 password: 'PASSWORD'